#!/usr/bin/env python
# -- coding: utf-8 --

import json
import requests
from sseclient import SSEClient as EventSource
import login

url = 'https://stream.wikimedia.org/v2/stream/revision-create'
API_url = "https://ru.wikinews.org/w/api.php"

for event in EventSource(url):
    if event.event == 'message':
        try:
            change = json.loads(event.data)
        except ValueError:
            pass
        else:
            if change["database"] == "ruwikinews" and change["page_namespace"] == 0 and "rev_parent_id" not in change:
                token, cookies = login.login(server="ru.wikinews")
                params = {
                    "action": "edit", "format": "json", "utf8": "1", "title": "Комментарии:" + change["page_title"],
                    "createonly": 1, "text": "{{комментарии2}} <!-- Оставьте эту строчку. Пишите комментарий ниже. -->",
                    "summary": "", "token": token
                }
                requests.post(url=API_url, params=params, cookies=cookies)
