#!/usr/bin/env python
# -- coding: utf-8 --

import json
import time
import requests
from sseclient import SSEClient as EventSource
import login

url = 'https://stream.wikimedia.org/v2/stream/revision-create'
API_url = "https://ru.wikinews.org/w/api.php"


def handler(change):
    if change["database"] == "ruwikinews" and "rev_parent_id" not in change and change["page_is_redirect"] == False:
        if change["page_namespace"] == 0 or change["page_namespace"] == 14:
            token, cookies = login.login(server="ru.wikinews")
            params = {"action": "edit", "format": "json", "utf8": "1", "createonly": 1, "token": token}
            if change["page_namespace"] == 0:
                params["title"] = "Комментарии:" + str(change["page_title"])
                params["text"] = "{{комментарии2}} <!-- Оставьте эту строчку. Пишите комментарий ниже. -->"
                params["summary"] = "Создание страницы комментариев"
            if change["page_namespace"] == 14:
                params["title"] = str(change["page_title"]).replace("Категория:", "")
                params["text"] = "#перенаправление [[" + str(change["page_title"]) + "]]"
                params["summary"] = "Создание перенаправления для категории"
            requests.post(url=API_url, data=params, cookies=cookies)


def start():
    try:
        for event in EventSource(url, retry=30000):
            if event.event == 'message':
                try:
                    change = json.loads(event.data)
                except ValueError:
                    pass
                else:
                    handler(change)
    except Exception:
        print("HTTP error")
        time.sleep(30)
        start()


start()
